# Site
title: Coop's Code
email: cbrislain@gmail.com
description: >-
  Real-Time Visuals, IOT for VanLife, Flashy Lights and other Mad Science
baseurl: ""
url: "https://spaceboycoop.github.io"
bio: >-
  Real-Time Visuals, IOT for VanLife, Flashy Lights and other Mad Science
locale: en_US

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author: SpaceboyCoop

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       UA-121066483-1
twitter:            spaceboycoop
facebook:           spaceboycoop
instagram:          spaceboycoop
github:             spaceboycoop

# personal
location:           Oakland, CA
phone:              707.742.3731
email:              cbrislain@gmail.com

plugins:
  - jekyll-feed
  - jekyll-avatar
  - jemoji
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
